# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-17 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='blurb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='rating_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
