# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-17 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0002_auto_20181017_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='blurb',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
