# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0003_auto_20181017_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='blurb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=600),
        ),
    ]
