# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-17 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0004_auto_20181017_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.URLField(max_length=600),
        ),
    ]
